teleop:
  next_waypoint:
    type: service
    service_name: /waypoint_manager/waypoint_server/next_waypoint
    buttons: [2,8]
  switch_cancel:
    type: service
    service_name: /waypoint_manager/waypoint_server/switch_cancel
    buttons: [3,8]
  control_mode_open_free:
    type: topic
    message_type: ypspur_ros/ControlMode
    topic_name: /control_mode
    deadman_buttons: [1,4]
    message_value:
     -
       target: vehicle_control_mode
       value: 0
  control_mode_velocity:
    type: topic
    message_type: ypspur_ros/ControlMode
    topic_name: /control_mode
    deadman_buttons: [0,4]
    message_value:
     -
       target: vehicle_control_mode
       value: 2
